apiVersion: v1
kind: Service
metadata:
  name: cowsay-service
spec:
  selector:
    app: cowsay
  ports:
    - protocol: TCP
      port: 80
      targetPort:  {{ .Values.service.port }}
  type: LoadBalancer
