apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cowsay-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host:
      http:
        paths:
          - path: {{ .Values.ingress.path }}(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: cowsay-service
                port:
                  number: 80
