# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
---
replicaCount: 2
port: 3000
image:
  repository: localhost:59391/invoice-service
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

env:
  LOG_LEVEL: "info"
  POSTGRES_PASSWORD: "p4ssw0rd"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  hosts:
    - host:
      paths:
        - pathType: Prefix
          path: /exercise-three/invoice(/|$)(.*)
          backend:
            service:
              name: invoice-service
              port:
                number: 80
