name: Build on macOS
on: push

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install Docker
        run: brew install docker
      - name: Run Setup
        run: zsh setup.zsh
      - name: Validate Exercise One
        run: curl localhost/exercise-one/cowsay
      - name: Validate Exercise Two
        run: curl localhost/exercise-two/cowsay
      - name: Fix Exercise Three
        run: |
          helm upgrade --install invoice-service exercise-three/invoice-service/chart -n exercise-three --debug
          helm rollback download-service -n exercise-three
          sleep 10
      - name: Validate Exercise Three
        run: |
          curl localhost/exercise-three/user/users
          curl localhost/exercise-three/invoice/invoices
          curl localhost/exercise-three/download/download
      - name: Teardown
        run: zsh teardown.zsh
