name: Build on macOS
on: push

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install Docker
        run: brew install docker
      - name: Run Setup
        run: zsh setup.zsh
      - name: Teardown
        run: zsh teardown.zsh